export {
  generateTempSpark,
  generateSunshineSpark,
  generatePrecipSpark,
  getLastNReadings,
  formatSunshinePercent,
  formatPrecipitation,
  formatTemperature,
  formatWindSpeed,
  formatWindDirection,
  getWindSpeedColor,
  formatTime,
  getHourLabels,
  type SparkData,
} from "./formatting";
